apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appname }}
spec:
  minAvailable: {{ .Values.PodDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}